# Generated by Django 5.0.3 on 2024-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
