# Generated by Django 5.0.3 on 2024-03-13 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('DOB', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprenticeLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('apprentice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applife', to='employees.apprentice')),
            ],
        ),
        migrations.CreateModel(
            name='ApprenticeRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('apprentice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approot', to='employees.apprentice')),
            ],
        ),
    ]
